<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [25]:
py_list=["a1", "b2", "c3", "d4", "e5",
         "f6", "g7", "h8", "i9", "j10"]
np_array=np.array(py_list)

x = np_array

print(x)

['a1' 'b2' 'c3' 'd4' 'e5' 'f6' 'g7' 'h8' 'i9' 'j10']


In [26]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [27]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [28]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [29]:
np_array[~(np_array > 3)]  

array([1, 2, 3])

### 1.3 Indexing & Slicing 2D Lists

In [30]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

py_list_2d[:3]

[[1, 'A'], [2, 'B'], [3, 'C']]

### 1.4 Indexing & Slicing 2D Arrays

In [31]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

np_array_2d[:3]

array([['1', 'A'],
       ['2', 'B'],
       ['3', 'C']], dtype='<U21')

### 1.5 Growing lists

In [33]:
x=[1]*10
x

x=[1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

In [34]:
a=(1, 2, 3)

print(a[0])

1


In [35]:
a[0]=-1

#Not possible with tuples

TypeError: 'tuple' object does not support item assignment

### 2.2 Be VERY careful when copying

In [36]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

- **Subsetting:** An umbrella term entailing selecting data from a dataset
- **Indexing:** A type of subsetting involving selecting an individual datapoint
- **Slicing:** A type of subsetting involving selecting a range of datapoints
- **Masking:** *Subsetting which involves selecting datapoints which meet a specific condition*

## Exercise 2 :  Show me the ‘odd’ letters

In [16]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

np_array_2d[:, 0]

x=np_array_2d[:, 0]
print(x.astype(int))

[ 1  3  2  4  5  7  6  8 10  9]


In [17]:
x.astype(int)%2

array([1, 1, 0, 0, 1, 1, 0, 0, 0, 1])

In [21]:
rem_array = x.astype(int)%2
odd_mask = rem_array > 0
print(odd_mask)

[ True  True False False  True  True False False False  True]


In [22]:
odd_mask

array([ True,  True, False, False,  True,  True, False, False, False,
        True])

In [24]:
x[odd_mask]

array(['1', '3', '5', '7', '9'], dtype='<U21')